experiment fail first strategy

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -7,9 +7,16 @@ jobs:
   backward-compatibility:
     name: Backward compatibility ${{ matrix.os }}-${{ matrix.node-version }}
     strategy:
+      fail-fast: false # default value is true: if one failed, all the subsequent jobs will be cancelled
       matrix:
         os: [ubuntu-latest, windows-latest]
         node-version: [20.x, 18.x, 16.x]
+        include:
+          - os: ubuntu-latest
+            node-version: 16.x
+          - os: ubuntu-latest
+            node-version: 21.x
+            tag: experiment
     runs-on: ${{ matrix.os }}
     steps:
       - name: Checkout code
@@ -20,6 +27,16 @@ jobs:
         with:
           node-version: ${{ matrix.node-version }}
 
+      - name: Fail is experimental
+        if: ${{ matrix.tag == 'experiment' }}
+        run: |
+          echo "This is an experimental version"
+          exit 1
+
       - name: Perform some tests
         run: |
           echo "Running tests for OS ${{ matrix.os }} and Node.js: ${{ matrix.node-version }}"
+          sleep 10
+
+      - name: Upload test results
+        run: echo "Uploading test results"
